default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
witches-town: styles/witches-town.scss
cyberpunk-neon: styles/cyberpunk-neon.scss
neon-city: styles/neon-city.scss
